In [56]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [57]:
#Carga desde un archivo .csv sin indice
data = pd.read_csv('Rio.csv')
data.head(5)

,Unnamed: 0,source,name,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,0,city scrape,Unbelievable Ocean View Apartment,2011-11-19,"Rio de Janeiro, Brazil",a few days or more,0%,0%,f,Vidigal,...,4.33,4.67,4.33,4.00,f,1,1,0,0,0.05
1,1,city scrape,EXCELENTE APARTAMENTO EM COPACABANA,2013-07-15,"Rio de Janeiro, Brazil",NaN,NaN,NaN,f,NaN,...,4.97,4.97,4.97,4.86,t,2,2,0,0,2.31
2,2,city scrape,Comfort em Copacabana,2011-11-20,"Rio de Janeiro, Brazil",within an hour,100%,100%,t,Copacabana,...,4.94,5.00,4.97,4.94,t,5,3,2,0,0.25
3,3,city scrape,Amazing Huge Apartment in Leblon,2011-04-25,"Rio de Janeiro, Brazil",NaN,NaN,NaN,f,Leblon,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
4,4,city scrape,Lindo quarto sossegado para temporada,2011-05-04,"Rio de Janeiro, Brazil",within a few hours,100%,20%,f,Santa Teresa,...,5.00,5.00,4.60,4.80,f,5,0,5,0,0.04

In [58]:
#Eliminar columnas innecesarias
#axis = 1 para columnas
#axis = 0 para filas
data2= data.drop(["Unnamed: 0"], axis=1)
data2

,source,name,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,city scrape,Unbelievable Ocean View Apartment,2011-11-19,"Rio de Janeiro, Brazil",a few days or more,0%,0%,f,Vidigal,1.0,...,4.33,4.67,4.33,4.00,f,1,1,0,0,0.05
1,city scrape,EXCELENTE APARTAMENTO EM COPACABANA,2013-07-15,"Rio de Janeiro, Brazil",NaN,NaN,NaN,f,NaN,3.0,...,4.97,4.97,4.97,4.86,t,2,2,0,0,2.31
2,city scrape,Comfort em Copacabana,2011-11-20,"Rio de Janeiro, Brazil",within an hour,100%,100%,t,Copacabana,6.0,...,4.94,5.00,4.97,4.94,t,5,3,2,0,0.25
3,city scrape,Amazing Huge Apartment in Leblon,2011-04-25,"Rio de Janeiro, Brazil",NaN,NaN,NaN,f,Leblon,1.0,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
4,city scrape,Lindo quarto sossegado para temporada,2011-05-04,"Rio de Janeiro, Brazil",within a few hours,100%,20%,f,Santa Teresa,5.0,...,5.00,5.00,4.60,4.80,f,5,0,5,0,0.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39494,city scrape,Copa Reformado 1 qrt perto do metrô,2014-06-27,"Rio de Janeiro, Brazil",within an hour,100%,99%,NaN,Copacabana,25.0,...,NaN,NaN,NaN,NaN,f,20,20,0,0,NaN
39495,city scrape,Casa Sabiá,2022-08-24,NaN,NaN,NaN,NaN,f,Cachambi,1.0,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
39496,city scrape,Apartamento na Barata Ribeiro - Copacabana,2020-03-07,"State of Rio de Janeiro, Brazil",within an hour,100%,100%,f,Copacabana,1.0,...,NaN,NaN,NaN,NaN,t,1,1,0,0,NaN
39497,city scrape,No coração de Ipanema…,2016-04-14,"State of Rio de Janeiro, Brazil",within an hour,100%,100%,f,Ipanema,1.0,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
39498,city scrape,Aconchego de Copanema!,2016-03-08,"Rio de Janeiro, Brazil",NaN,NaN,NaN,f,Copacabana,1.0,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN

In [59]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39499 entries, 0 to 39498
Data columns (total 50 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   source                                        39499 non-null  object
 1   name                                          39499 non-null  object
 2   host_since                                    39497 non-null  object
 3   host_location                                 31853 non-null  object
 4   host_response_time                            35578 non-null  object
 5   host_response_rate                            35578 non-null  object
 6   host_acceptance_rate                          35965 non-null  object
 7   host_is_superhost                             38329 non-null  object
 8   host_neighbourhood                            33964 non-null  object
 9   host_listings_count                           39497 non-null  float64
 10  host_total_listings_count                     39497 non-null  float64
 11  host_identity_verified                        39497 non-null  object
 12  neighbourhood                                 16880 non-null  object
 13  neighbourhood_cleansed                        39499 non-null  object
 14  property_type                                 39499 non-null  object
 15  room_type                                     39499 non-null  object
 16  accommodates                                  39499 non-null  int64
 17  bathrooms                                     36609 non-null  float64
 18  bedrooms                                      38976 non-null  float64
 19  beds                                          36630 non-null  float64
 20  price                                         36644 non-null  object
 21  minimum_nights                                39499 non-null  int64
 22  maximum_nights                                39499 non-null  int64
 23  minimum_minimum_nights                        39499 non-null  int64
 24  maximum_minimum_nights                        39499 non-null  int64
 25  minimum_maximum_nights                        39499 non-null  int64
 26  maximum_maximum_nights                        39499 non-null  int64
 27  has_availability                              39002 non-null  object
 28  availability_30                               39499 non-null  int64
 29  availability_60                               39499 non-null  int64
 30  availability_90                               39499 non-null  int64
 31  availability_365                              39499 non-null  int64
 32  number_of_reviews                             39499 non-null  int64
 33  number_of_reviews_ltm                         39499 non-null  int64
 34  number_of_reviews_l30d                        39499 non-null  int64
 35  first_review                                  29080 non-null  object
 36  last_review                                   29080 non-null  object
 37  review_scores_rating                          29080 non-null  float64
 38  review_scores_accuracy                        29079 non-null  float64
 39  review_scores_cleanliness                     29080 non-null  float64
 40  review_scores_checkin                         29079 non-null  float64
 41  review_scores_communication                   29079 non-null  float64
 42  review_scores_location                        29078 non-null  float64
 43  review_scores_value                           29079 non-null  float64
 44  instant_bookable                              39499 non-null  object
 45  calculated_host_listings_count                39499 non-null  int64
 46  calculated_host_listings_count_entire_homes   39499 non-null  int64
 47  calculated_host_listings_count_private_rooms  39499 non-null  int64
 48  calculated_host_listings_count_shared_rooms   39499 non-null  int64
 49  reviews_per_month                             29080 non-null  float64
dtypes: float64(13), int64(18), object(19)
memory usage: 15.1+ MB

In [60]:
#Asignamos el nombre "dataframe" a nuestra base de datos
dataframe=data2

## ***Función para identificar valores nulos***

In [63]:
def cuenta_valores_nulos(dataframe):
    #Valores nulos por columna
    valores_nulos_cols = dataframe.isnull().sum()
    #Valores nulos por dataframe
    valores_nulos_df = dataframe.isnull().sum().sum()
    
    return("Valores nulos por columna:", valores_nulos_cols,
            "Valores nulos por dataframe: ", valores_nulos_df)

In [64]:
# Llamamos a la función "cuenta_valores_nulos" y guardamos el retorno
cuenta_valores_nulos(dataframe)

('Valores nulos por columna:',
 source                                              0
 name                                                0
 host_since                                          2
 host_location                                    7646
 host_response_time                               3921
 host_response_rate                               3921
 host_acceptance_rate                             3534
 host_is_superhost                                1170
 host_neighbourhood                               5535
 host_listings_count                                 2
 host_total_listings_count                           2
 host_identity_verified                              2
 neighbourhood                                   22619
 neighbourhood_cleansed                              0
 property_type                                       0
 room_type                                           0
 accommodates                                        0
 bathrooms                                        2890
 bedrooms                                          523
 beds                                             2869
 price                                            2855
 minimum_nights                                      0
 maximum_nights                                      0
 minimum_minimum_nights                              0
 maximum_minimum_nights                              0
 minimum_maximum_nights                              0
 maximum_maximum_nights                              0
 has_availability                                  497
 availability_30                                     0
 availability_60                                     0
 availability_90                                     0
 availability_365                                    0
 number_of_reviews                                   0
 number_of_reviews_ltm                               0
 number_of_reviews_l30d                              0
 first_review                                    10419
 last_review                                     10419
 review_scores_rating                            10419
 review_scores_accuracy                          10420
 review_scores_cleanliness                       10419
 review_scores_checkin                           10420
 review_scores_communication                     10420
 review_scores_location                          10421
 review_scores_value                             10420
 instant_bookable                                    0
 calculated_host_listings_count                      0
 calculated_host_listings_count_entire_homes         0
 calculated_host_listings_count_private_rooms        0
 calculated_host_listings_count_shared_rooms         0
 reviews_per_month                               10419
 dtype: int64,
 'Valores nulos por dataframe: ',
 162184)

## a) Reemplazar valores nulos con el método de “mediana” en las columnas tipo “numeric (int y float)”

In [65]:
def sustitución_mediana(dataframe):
    #Separo columnas cuantitativas del dataframe
    cuantitativas_con_nulos = dataframe.select_dtypes(include=['float64', 'int64','float','int'])
    #Separo columnas cualitativas del dataframe
    cualitativas = dataframe.select_dtypes(include=['object', 'datetime','category'])
    #Sustituir valores nulos con promedio o media
    cuantitativas = cuantitativas_con_nulos.fillna(round(cuantitativas_con_nulos.median(), 1))
    # Unimos el dataframe cuantitativo limpio con el dataframe cualitativo
    Datos_sin_nulos = pd.concat([cuantitativas, cualitativas], axis=1)
    
    return(Datos_sin_nulos)

In [66]:
# Llamamos a la función "cuenta_valores_nulos" y guardamos el retorno
dataframe_sin_nulos_a=sustitución_mediana(dataframe)

In [67]:
# Llamamos a la función "cuenta_valores_nulos" y guardamos el retorno
cuenta_valores_nulos(dataframe_sin_nulos_a)

('Valores nulos por columna:',
 host_listings_count                                 0
 host_total_listings_count                           0
 accommodates                                        0
 bathrooms                                           0
 bedrooms                                            0
 beds                                                0
 minimum_nights                                      0
 maximum_nights                                      0
 minimum_minimum_nights                              0
 maximum_minimum_nights                              0
 minimum_maximum_nights                              0
 maximum_maximum_nights                              0
 availability_30                                     0
 availability_60                                     0
 availability_90                                     0
 availability_365                                    0
 number_of_reviews                                   0
 number_of_reviews_ltm                               0
 number_of_reviews_l30d                              0
 review_scores_rating                                0
 review_scores_accuracy                              0
 review_scores_cleanliness                           0
 review_scores_checkin                               0
 review_scores_communication                         0
 review_scores_location                              0
 review_scores_value                                 0
 calculated_host_listings_count                      0
 calculated_host_listings_count_entire_homes         0
 calculated_host_listings_count_private_rooms        0
 calculated_host_listings_count_shared_rooms         0
 reviews_per_month                                   0
 source                                              0
 name                                                0
 host_since                                          2
 host_location                                    7646
 host_response_time                               3921
 host_response_rate                               3921
 host_acceptance_rate                             3534
 host_is_superhost                                1170
 host_neighbourhood                               5535
 host_identity_verified                              2
 neighbourhood                                   22619
 neighbourhood_cleansed                              0
 property_type                                       0
 room_type                                           0
 price                                            2855
 has_availability                                  497
 first_review                                    10419
 last_review                                     10419
 instant_bookable                                    0
 dtype: int64,
 'Valores nulos por dataframe: ',
 72540)

## b) Reemplazar valores nulos con el método de “ffill” en las columnas tipo “object, datetime y category”

In [68]:
def sustitución_ffill(dataframe):
    #Separo columnas cuantitativas del dataframe
    cuantitativas = dataframe.select_dtypes(include=['float64', 'int64','float','int'])
    #Separo columnas cualitativas del dataframe
    cualitativas_con_nulos = dataframe.select_dtypes(include=['object', 'datetime','category'])
    #Sustituir valores nulos con promedio o media
    cualitativas = cualitativas_con_nulos.fillna(method="ffill")
    # Unimos el dataframe cuantitativo limpio con el dataframe cualitativo
    Datos_sin_nulos = pd.concat([cuantitativas, cualitativas], axis=1)
    
    return(Datos_sin_nulos)

In [69]:
# Llamamos a la función "cuenta_valores_nulos" y guardamos el retorno
dataframe_sin_nulos_b=sustitución_ffill(dataframe)

/var/folders/g2/ww78rm_s75z1d2tynldmz1_m0000gn/T/ipykernel_4956/3518203831.py:7: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  cualitativas = cualitativas_con_nulos.fillna(method="ffill")

In [70]:
# Llamamos a la función "cuenta_valores_nulos" y guardamos el retorno
cuenta_valores_nulos(dataframe_sin_nulos_b)

('Valores nulos por columna:',
 host_listings_count                                 2
 host_total_listings_count                           2
 accommodates                                        0
 bathrooms                                        2890
 bedrooms                                          523
 beds                                             2869
 minimum_nights                                      0
 maximum_nights                                      0
 minimum_minimum_nights                              0
 maximum_minimum_nights                              0
 minimum_maximum_nights                              0
 maximum_maximum_nights                              0
 availability_30                                     0
 availability_60                                     0
 availability_90                                     0
 availability_365                                    0
 number_of_reviews                                   0
 number_of_reviews_ltm                               0
 number_of_reviews_l30d                              0
 review_scores_rating                            10419
 review_scores_accuracy                          10420
 review_scores_cleanliness                       10419
 review_scores_checkin                           10420
 review_scores_communication                     10420
 review_scores_location                          10421
 review_scores_value                             10420
 calculated_host_listings_count                      0
 calculated_host_listings_count_entire_homes         0
 calculated_host_listings_count_private_rooms        0
 calculated_host_listings_count_shared_rooms         0
 reviews_per_month                               10419
 source                                              0
 name                                                0
 host_since                                          0
 host_location                                       0
 host_response_time                                  0
 host_response_rate                                  0
 host_acceptance_rate                                0
 host_is_superhost                                   0
 host_neighbourhood                                  0
 host_identity_verified                              0
 neighbourhood                                       0
 neighbourhood_cleansed                              0
 property_type                                       0
 room_type                                           0
 price                                               0
 has_availability                                    0
 first_review                                        0
 last_review                                         0
 instant_bookable                                    0
 dtype: int64,
 'Valores nulos por dataframe: ',
 89644)

## c) Reemplazar valores nulos con el método de “bfill” en las columnas tipo “object, datetime y category”

In [71]:
def sustitución_bfill(dataframe):
    #Separo columnas cuantitativas del dataframe
    cuantitativas = dataframe.select_dtypes(include=['float64', 'int64','float','int'])
    #Separo columnas cualitativas del dataframe
    cualitativas_con_nulos = dataframe.select_dtypes(include=['object', 'datetime','category'])
    #Sustituir valores nulos con promedio o media
    cualitativas = cualitativas_con_nulos.fillna(method="bfill")
    # Unimos el dataframe cuantitativo limpio con el dataframe cualitativo
    Datos_sin_nulos = pd.concat([cuantitativas, cualitativas], axis=1)
    
    return(Datos_sin_nulos)

In [72]:
# Llamamos a la función "cuenta_valores_nulos" y guardamos el retorno
dataframe_sin_nulos_c=sustitución_bfill(dataframe)

/var/folders/g2/ww78rm_s75z1d2tynldmz1_m0000gn/T/ipykernel_4956/62740553.py:7: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  cualitativas = cualitativas_con_nulos.fillna(method="bfill")

In [73]:
# Llamamos a la función "cuenta_valores_nulos" y guardamos el retorno
cuenta_valores_nulos(dataframe_sin_nulos_b)

('Valores nulos por columna:',
 host_listings_count                                 2
 host_total_listings_count                           2
 accommodates                                        0
 bathrooms                                        2890
 bedrooms                                          523
 beds                                             2869
 minimum_nights                                      0
 maximum_nights                                      0
 minimum_minimum_nights                              0
 maximum_minimum_nights                              0
 minimum_maximum_nights                              0
 maximum_maximum_nights                              0
 availability_30                                     0
 availability_60                                     0
 availability_90                                     0
 availability_365                                    0
 number_of_reviews                                   0
 number_of_reviews_ltm                               0
 number_of_reviews_l30d                              0
 review_scores_rating                            10419
 review_scores_accuracy                          10420
 review_scores_cleanliness                       10419
 review_scores_checkin                           10420
 review_scores_communication                     10420
 review_scores_location                          10421
 review_scores_value                             10420
 calculated_host_listings_count                      0
 calculated_host_listings_count_entire_homes         0
 calculated_host_listings_count_private_rooms        0
 calculated_host_listings_count_shared_rooms         0
 reviews_per_month                               10419
 source                                              0
 name                                                0
 host_since                                          0
 host_location                                       0
 host_response_time                                  0
 host_response_rate                                  0
 host_acceptance_rate                                0
 host_is_superhost                                   0
 host_neighbourhood                                  0
 host_identity_verified                              0
 neighbourhood                                       0
 neighbourhood_cleansed                              0
 property_type                                       0
 room_type                                           0
 price                                               0
 has_availability                                    0
 first_review                                        0
 last_review                                         0
 instant_bookable                                    0
 dtype: int64,
 'Valores nulos por dataframe: ',
 89644)

## d) Reemplazar valores nulos con el método de “string concreto” en las columnas tipo “object, datetime y category”

In [74]:
def sustitución_string(dataframe):
    #Separo columnas cuantitativas del dataframe
    cuantitativas = dataframe.select_dtypes(include=['float64', 'int64','float','int'])
    #Separo columnas cualitativas del dataframe
    cualitativas_con_nulos = dataframe.select_dtypes(include=['object', 'datetime','category'])
    #Sustituir valores nulos con promedio o media
    cualitativas = cualitativas_con_nulos.fillna("Sin registro")
    # Unimos el dataframe cuantitativo limpio con el dataframe cualitativo
    Datos_sin_nulos = pd.concat([cuantitativas, cualitativas], axis=1)
    
    return(Datos_sin_nulos)

In [75]:
# Llamamos a la función "cuenta_valores_nulos" y guardamos el retorno
dataframe_sin_nulos_d=sustitución_string(dataframe)

In [76]:
# Llamamos a la función "cuenta_valores_nulos" y guardamos el retorno
cuenta_valores_nulos(dataframe_sin_nulos_d)

('Valores nulos por columna:',
 host_listings_count                                 2
 host_total_listings_count                           2
 accommodates                                        0
 bathrooms                                        2890
 bedrooms                                          523
 beds                                             2869
 minimum_nights                                      0
 maximum_nights                                      0
 minimum_minimum_nights                              0
 maximum_minimum_nights                              0
 minimum_maximum_nights                              0
 maximum_maximum_nights                              0
 availability_30                                     0
 availability_60                                     0
 availability_90                                     0
 availability_365                                    0
 number_of_reviews                                   0
 number_of_reviews_ltm                               0
 number_of_reviews_l30d                              0
 review_scores_rating                            10419
 review_scores_accuracy                          10420
 review_scores_cleanliness                       10419
 review_scores_checkin                           10420
 review_scores_communication                     10420
 review_scores_location                          10421
 review_scores_value                             10420
 calculated_host_listings_count                      0
 calculated_host_listings_count_entire_homes         0
 calculated_host_listings_count_private_rooms        0
 calculated_host_listings_count_shared_rooms         0
 reviews_per_month                               10419
 source                                              0
 name                                                0
 host_since                                          0
 host_location                                       0
 host_response_time                                  0
 host_response_rate                                  0
 host_acceptance_rate                                0
 host_is_superhost                                   0
 host_neighbourhood                                  0
 host_identity_verified                              0
 neighbourhood                                       0
 neighbourhood_cleansed                              0
 property_type                                       0
 room_type                                           0
 price                                               0
 has_availability                                    0
 first_review                                        0
 last_review                                         0
 instant_bookable                                    0
 dtype: int64,
 'Valores nulos por dataframe: ',
 89644)

## e) Reemplazar valores nulos con el método de “constante” en las columnas tipo “numeric (int y float)”

In [77]:
def sustitución_constante(dataframe):
    #Separo columnas cuantitativas del dataframe
    cuantitativas_con_nulos = dataframe.select_dtypes(include=['float64', 'int64','float','int'])
    #Separo columnas cualitativas del dataframe
    cualitativas = dataframe.select_dtypes(include=['object', 'datetime','category'])
    #Sustituir valores nulos con promedio o media
    cuantitativas = cuantitativas_con_nulos.fillna(10)
    # Unimos el dataframe cuantitativo limpio con el dataframe cualitativo
    Datos_sin_nulos = pd.concat([cuantitativas, cualitativas], axis=1)
    
    return(Datos_sin_nulos)

In [78]:
# Llamamos a la función "cuenta_valores_nulos" y guardamos el retorno
dataframe_sin_nulos_e=sustitución_constante(dataframe)

In [79]:
# Llamamos a la función "cuenta_valores_nulos" y guardamos el retorno
cuenta_valores_nulos(dataframe_sin_nulos_e)

('Valores nulos por columna:',
 host_listings_count                                 0
 host_total_listings_count                           0
 accommodates                                        0
 bathrooms                                           0
 bedrooms                                            0
 beds                                                0
 minimum_nights                                      0
 maximum_nights                                      0
 minimum_minimum_nights                              0
 maximum_minimum_nights                              0
 minimum_maximum_nights                              0
 maximum_maximum_nights                              0
 availability_30                                     0
 availability_60                                     0
 availability_90                                     0
 availability_365                                    0
 number_of_reviews                                   0
 number_of_reviews_ltm                               0
 number_of_reviews_l30d                              0
 review_scores_rating                                0
 review_scores_accuracy                              0
 review_scores_cleanliness                           0
 review_scores_checkin                               0
 review_scores_communication                         0
 review_scores_location                              0
 review_scores_value                                 0
 calculated_host_listings_count                      0
 calculated_host_listings_count_entire_homes         0
 calculated_host_listings_count_private_rooms        0
 calculated_host_listings_count_shared_rooms         0
 reviews_per_month                                   0
 source                                              0
 name                                                0
 host_since                                          2
 host_location                                    7646
 host_response_time                               3921
 host_response_rate                               3921
 host_acceptance_rate                             3534
 host_is_superhost                                1170
 host_neighbourhood                               5535
 host_identity_verified                              2
 neighbourhood                                   22619
 neighbourhood_cleansed                              0
 property_type                                       0
 room_type                                           0
 price                                            2855
 has_availability                                  497
 first_review                                    10419
 last_review                                     10419
 instant_bookable                                    0
 dtype: int64,
 'Valores nulos por dataframe: ',
 72540)

### Archivos csv

In [81]:
dataframe_sin_nulos_a.to_csv("Act3.2_a.csv")
dataframe_sin_nulos_b.to_csv("Act3.2_b.csv")
dataframe_sin_nulos_c.to_csv("Act3.2_c.csv")
dataframe_sin_nulos_d.to_csv("Act3.2_d.csv")
dataframe_sin_nulos_e.to_csv("Act3.2_e.csv")